version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8000:80"
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
networks:
  internal:
    driver: bridge